# NOTE: Nerd fonts are required!
# This configuration is works well with "FiraCode NF" font
# Download from: https://www.nerdfonts.com/

# NOTE: Warning, the module "battery" lags terribly in PowerShell

# ============================================================================ #
# Default configuration
# ============================================================================ #

# The newline at the start of the prompt
add_newline = false

# Wait 10 milliseconds for starship to check files under the current directory.
scan_timeout = 10

# Overwrite the default format
format = """
┌\
	$username\
	$hostname\
	$time\
	$cmd_duration\
	$nodejs\
	$deno\
	$python\
	$rustgolang\
	$memory_usage\
	$line_break\
├\
	$directory\
	$git_branch\
	$git_commit\
	$git_state\
	$git_status\
	$git_metrics\
	$package\
	$line_break\
└\
	$jobs\
	$status\
	$character\
"""

# ============================================================================ #
# Modules
# ============================================================================ #

# ---------------------------------------------------------------------------- #
#                                                                   Line nr 1
#                                                     Environment information
# ---------------------------------------------------------------------------- #

# https://starship.rs/config/#username
[username]
	disabled    = false
	style_user  = "bg:purple fg:bright-white"
	format      = "[](fg:purple)[ $user]($style)"
	show_always = true

# https://starship.rs/config/#hostname
[hostname]
	disabled = false
	style    = "bg:purple fg:bright-white"
	format   = "[@$hostname]($style)[](fg:purple)"
	trim_at  = "."
	ssh_only = false

# https://starship.rs/config/#time
[time]
	disabled        = false
	style           = "fg:black bg:white"
	format          = " [](fg:white)[ $time]($style)[](fg:white)"
	utc_time_offset = "local"
	time_range      = "-"
	use_12hr        = true

# https://starship.rs/config/#command-duration
[cmd_duration]
	disabled           = false
	style              = "fg:blue"
	format             = "[ 祥$duration]($style)"
	min_time           = 100
	show_milliseconds  = true
	show_notifications = true
	min_time_to_notify = 10_000

# https://starship.rs/config/#battery
[battery]
	disabled           = false
	format             = " [$symbol ](fg:white)[$percentage]($style)[](fg:white)"
	full_symbol        = ""
	charging_symbol    = ""
	discharging_symbol = ""
	unknown_symbol     = ""
	empty_symbol       = ""
	[[battery.display]]
		threshold = 50
		style     = "bg:white fg:red"
	[[battery.display]]
		threshold = 75
		style     = "bg:white fg:yellow"
	[[battery.display]]
		threshold = 90
		style     = "bg:white fg:green"

# https://starship.rs/config/#python
[python]
	disabled           = false
	style              = "bg:bright-yellow fg:blue"
	# pyenv_version_name = true
	# pyenv_prefix       = true
	format             = " [](fg:bright-yellow)[$symbol $version]($style)[](fg:bright-yellow)"
	symbol             = ""

# https://starship.rs/config/#nodejs

[nodejs]
	disabled          = false
	style             = "bg:green fg:bright-white"
	not_capable_style = "bold red"
	format            = " [](fg:green)[$symbol $version]($style)[](fg:green)"
	symbol            = ""

# https://starship.rs/config/#nodejs
[deno]
	disabled          = false
	style             = "bg:white fg:black"
	format            = " [](fg:white)[$symbol$version]($style)[](fg:white)"
	version_format    = "v${raw}"
	detect_extensions = []
	detect_files      = ["mod.ts", "mod.js", "deps.ts", "deps.js"]
	detect_folders    = []
	symbol            = "硫"

# https://starship.rs/config/#rust
[rust]
	disabled          = false
	style             = "bg:bright-black fg:bright-white"
	format            = " [](fg:bright-black)[$symbol $version]($style)[](fg:bright-black)"
	symbol            = ""

# https://starship.rs/config/#golang
[golang]
	disabled          = false
	style             = "bg:cyan fg:bright-white"
	format            = " [](fg:cyan)[$symbol $version]($style)[](fg:cyan)"
	symbol            = ""

# https://starship.rs/config/#memory-usage
[memory_usage]
	disabled        = false
	style           = "bg:yellow fg:bright-white"
	format          = "[  ](fg:yellow)[$symbol ${ram_pct}|${swap_pct}]($style)[](fg:yellow)"
	symbol          = ""
	threshold       = 50

# ---------------------------------------------------------------------------- #
#                                                                   Line nr 2
#                                                 Directory & Git information
# ---------------------------------------------------------------------------- #

# https://starship.rs/config/#directory
[directory]
	disabled          = false
	style             = "bg:black fg:bright-white"
	format            = "[](fg:black)[ﱮ]($style)[$read_only]($read_only_style)[ $path]($style)[](fg:black)"
	truncation_length = 5
	truncate_to_repo  = true
	truncation_symbol = ".../"
	read_only         = " "
	read_only_style   = "fg:bright-red"

# https://starship.rs/config/#git-branch
[git_branch]
	disabled           = false
	style              = "bg:blue fg:bright-white"
	format             = " ﰲ [](fg:blue)[$symbol $branch]($style)[](fg:blue)"
	symbol             = ""
	always_show_remote = false
	truncation_length  = "2^63 - 1"
	truncation_symbol  = "..."
	only_attached      = true

# https://starship.rs/config/#git-commit
[git_commit]
	disabled           = false
	format             = " ﰲ [](fg:bright-red)[ﰖ $hash$tag]($style)[](fg:bright-red)"
	style              = "bg:bright-red fg:bright-white"
	only_detached      = true
	commit_hash_length = 8
	tag_disabled       = false
	tag_symbol         = "笠 "

# https://starship.rs/config/#git-state
[git_state]
	disabled         = false
	style            = "red"
	format           = '\([$state( $progress_current/$progress_total)]($style)\) '
	rebase           = " REBASING"
	merge            = " MERGING"
	revert           = " REVERTING"
	cherry_pick      = " PICKING"
	bisect           = " BISECTING"
	am               = "APPLY-MAILBOX"
	am_or_rebase     = "APPLY-MAILBOX / REBASE"

# https://starship.rs/config/#git-metrics
[git_metrics]
	disabled      = false
	added_style   = "bold green"
	deleted_style = "bold red"
	format        = ' [+$added]($added_style) [-$deleted]($deleted_style) '

# https://starship.rs/config/#git-status
[git_status]
	disabled   = false
	style      = "fg:blue"
	format     = "$ahead_behind$all_status"
	conflicted = "[ Conflicted ${count}](fg:red)"
	ahead      = "[⇡ﰛ Ahead ${count}](fg:blue)"
	behind     = "[⇣ﰛ Behind ${count}](fg:yello)"
	diverged   = "[ Diverged - ⇡ﰛ A ${ahead_count} | ⇣ﰚ B ${count}](fg:red)"
	untracked  = "[ ${count}](fg:bright-yellow)"
	stashed    = "[ ${count}](fg:bright-white)"
	modified   = "[ ${count}](fg:bright-purple)"
	staged     = "[ ${count}](fg:bright-green)"
	renamed    = "[ ${count}](fg:bright-cyan)"
	deleted    = "[ ${count}](fg:bright-red)"

# https://starship.rs/config/#package-version
[package]
	disabled        = false
	style           = "bg:white fg:black"
	format          = " ﰲ [](fg:white)[$symbol $version]($style)[](fg:white)"
	symbol          = ""
	display_private = true

# ---------------------------------------------------------------------------- #
#                                                                   Line nr 3
#                                                                Command line
# ---------------------------------------------------------------------------- #

# https://starship.rs/config/#jobs
[jobs]
	disabled  = false
	style     = "bg:green"
	format    = "[](fg:green)[$symbol $number]($style)[](fg:green)"
	symbol    = ""
	threshold = 1

# https://starship.rs/config/#status
[status]
	disabled              = false
	style                 = "bg:red"
	format                = "[](fg:red)[$symbol $int]($style)[](fg:red)"
	symbol                = ""
	sigint_symbol         = ""
	signal_symbol         = ""
	not_executable_symbol = ""
	not_found_symbol      = ""
	recognize_signal_code = true
	map_symbol            = true

# https://starship.rs/config/#character
[character]
	disabled              = false
	format                = "$symbol "
	success_symbol        = "[❯](fg:green)"
	error_symbol          = "[❯](fg:red)"
	vicmd_symbol          = "[❮](fg:yellow)"

