[[plugin.prepend_fetchers]]
url = "*"
run = "git"
group = "git"

[[plugin.prepend_fetchers]]
url = "*/"
run = "git"
group = "git"

# [[plugin.prepend_fetchers]]
# url = "local://*"
# run = "mime-ext.local"
# prio = "high"
# group = "mime"

[[plugin.prepend_fetchers]]
url = "remote://*"
run = "mime-ext.remote"
prio = "high"
group = "mime"
